apiVersion: v1
kind: Namespace
metadata:
  name: ray-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberay-operator
rules:
  - apiGroups: ["ray.io"]
    resources: ["rayclusters", "rayjobs", "rayservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberay-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberay-operator
subjects:
  - kind: ServiceAccount
    name: kuberay-operator
    namespace: ray-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberay-operator
  namespace: ray-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rayclusters.ray.io
spec:
  group: ray.io
  names:
    kind: RayCluster
    plural: rayclusters
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: ray-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberay-operator
  template:
    metadata:
      labels:
        app: kuberay-operator
    spec:
      serviceAccountName: kuberay-operator
      containers:
        - name: kuberay-operator
          image: kuberay/operator:v0.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
