apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: vatic-prop-ray
  namespace: default
spec:
  rayVersion: "2.9.0"
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: aggressive
    idleTimeoutSeconds: 300
  headGroupSpec:
    replicas: 1
    rayStartParams:
      port: "6379"
      object-manager-port: "12345"
      dashboard-host: "0.0.0.0"
      num-cpus: "4"
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.9.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
            resources:
              requests:
                cpu: 4
                memory: 8Gi
              limits:
                cpu: 4
                memory: 8Gi
            volumeMounts:
              - name: ray-logs
                mountPath: /tmp/ray
        volumes:
          - name: ray-logs
            emptyDir: {}
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 3
      minReplicas: 3
      maxReplicas: 10
      rayStartParams:
        num-cpus: "8"
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.9.0
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 8
                  memory: 16Gi
                limits:
                  cpu: 8
                  memory: 16Gi
              volumeMounts:
                - name: ray-logs
                  mountPath: /tmp/ray
          volumes:
            - name: ray-logs
              emptyDir: {}
  serviceType: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head-svc
  namespace: default
spec:
  selector:
    ray.io/cluster: vatic-prop-ray
    ray.io/node-type: head
  ports:
    - name: gcs
      port: 6379
      targetPort: 6379
    - name: dashboard
      port: 8265
      targetPort: 8265
    - name: client
      port: 10001
      targetPort: 10001
    - name: serve
      port: 8000
      targetPort: 8000
  type: ClusterIP
